server:
  port: 8082
################ 项目基本配置 ################
spring:
  application:
    # 对应注册Eureka中的服务名
    name: eureka

################ Eureka配置 ################
eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  client:
    # 防止Eureka启动时注册本身服务
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8081/eureka,http://localhost:8082/eureka